const subMonth = [
    {
        subImg: "one",
        subBread: "Rye",
        subToppings: ["Bacon, Lettuce, Cheese, Tomatoes"],
        subSauce: "Mustard",
        subName: "The Mustard in the Rye",
        subPrice: "R57.00",
        subCal: "315",   
    },
    {
        subImg: "two",
        subBread: "Wholewheat",
        subToppings: ["Bacon, Ham, Cheese, Feta"],
        subSauce: "Aioli Garlic",
        subName: "Salt Pan",
        subPrice: "R66.00",
        subCal: "402",   
    },
    {
        subImg: "three",
        subBread: "Multigrain",
        subToppings: ["Lettuce, Ham, Cheese"],
        subSauce: "Honey Mustard",
        subName: "Honey I'm Home",
        subPrice: "R48.00",
        subCal: "249",   
    },
    {
        subImg: "four",
        subBread: "Gluten Free",
        subToppings: ["Lettuce, Tomatoes, Olives"],
        subSauce: "Aioli Garlic",
        subName: "Food and Veg",
        subPrice: "R56.00",
        subCal: "225",   
    },
    {
        subImg: "five",
        subBread: "White Bread",
        subToppings: ["Bacon, Lettuce, Cheese, Olives"],
        subSauce: "Tomato Sauce",
        subName: "Porky Picnic",
        subPrice: "R71.00",
        subCal: "365",   
    },
    {
        subImg: "six",
        subBread: "Rye",
        subToppings: ["Cheese, Tomatoes, Ham"],
        subSauce: "Barbecue Sauce",
        subName: "BBQ for you",
        subPrice: "R52.00",
        subCal: "305",   
    },
    {
        subImg: "seven",
        subBread: "Gluten Free",
        subToppings: ["Cheese, Feta, Olives, Tomatoes"],
        subSauce: "Mustard",
        subName: "Cheesy Goodness",
        subPrice: "R58.00",
        subCal: "329",   
    },
    {
        subImg: "eight",
        subBread: "Multigrain",
        subToppings: ["Bacon, Lettuce, Tomatoes"],
        subSauce: "Mustard, Tomato Sauce",
        subName: "Yellow Submarine",
        subPrice: "R54.00",
        subCal: "291",   
    }

];
